[package]
name = "qorzen-oxide"
version = "0.1.0"
edition = "2021"
description = "A cross-platform, plugin-based application framework built with Rust and Dioxus"
license = "MIT OR Apache-2.0"
repository = "https://github.com/sssolid/QorzenOxide"
homepage = "https://qorzen.dev"
authors = ["Qorzen Team <team@qorzen.dev>"]

[dependencies]
# Core framework
dioxus = "0.5"
# Separate crates for different platforms
dioxus-desktop = { version = "0.5", optional = true }
dioxus-web = { version = "0.5", optional = true }
dioxus-router = { version = "0.5", optional = true }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
uuid = { version = "1.0", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }

# Error handling and logging
anyhow = "1.0"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = "0.2"

# Configuration
serde_yaml = "0.9"
toml = "0.8"

# Async utilities
futures = "0.3"
dashmap = "5.0"

# Networking
reqwest = { version = "0.11", features = ["json"] }

# File handling
notify = "6.0"
sha2 = "0.10"
flate2 = "1.0"

# CLI
clap = { version = "4.0", features = ["derive"] }

# System information
num_cpus = "1.0"
hostname = "0.3"

# Concurrency
crossbeam = "0.8"
parking_lot = "0.12"
rand = "0.9.1"
tokio-util = "0.7.15"

# Platform-specific dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
dirs = "5.0"
tempfile = "3.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
js-sys = "0.3"

[dev-dependencies]
tokio-test = "0.4"

[build-dependencies]
rustc_version = "0.4.1"

[features]
default = ["desktop"]
desktop = ["dioxus-desktop"]
web = ["dioxus-web"]
router = ["dioxus-router"]

[[bin]]
name = "qorzen-oxide"
path = "src/main.rs"

[lib]
name = "qorzen_oxide"
path = "src/lib.rs"