# Cargo.toml
[package]
name = "qorzen-core"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A modular plugin-based system with async core managers"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourusername/qorzen-core"
readme = "README.md"
keywords = ["async", "plugin", "system", "manager", "event-driven"]
categories = ["asynchronous", "development-tools"]

[dependencies]
# Async runtime and utilities
tokio = { version = "1.40", features = ["full"] }
tokio-util = "0.7"
futures = "0.3"
async-trait = "0.1"

# Serialization and configuration
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
toml = "0.8"
config = "0.14"

# Logging and observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-appender = { version = "0.2", optional = true }
tracing-opentelemetry = { version = "0.24", optional = true }

# Error handling
thiserror = "1.0"
anyhow = "1.0"
color-eyre = "0.6"

# File system operations
walkdir = "2.4"
sha2 = "0.10"
uuid = { version = "1.10", features = ["v4", "serde"] }

# Concurrency utilities
dashmap = "6.0"
parking_lot = "0.12"
crossbeam = "0.8"
crossbeam-channel = "0.5"
num_cpus = "1.16"

# Time and datetime
chrono = { version = "0.4", features = ["serde"] }

# Command line interface
clap = { version = "4.4", features = ["derive", "env"] }

# Random number generation
rand = "0.8"

# Compression
flate2 = "1.0"

# Networking (for future API features)
reqwest = { version = "0.12", features = ["json"] }
tower = "0.4"
hyper = "1.4"
hostname = "0.4"
notify = "8.0.0"

# Development dependencies
[dev-dependencies]
tokio-test = "0.4"
tempfile = "3.8"
proptest = "1.4"
criterion = "0.5"

[build-dependencies]
rustc_version = "0.4.1"

# Feature flags
[features]
default = ["json-logs", "file-rotation"]
json-logs = []
file-rotation = ["tracing-appender"]
metrics = ["tracing-opentelemetry"]

# Optimization profiles
[profile.release]
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
debug = true
opt-level = 0

[[bin]]
name = "qorzen"
path = "src/main.rs"

[lib]
name = "qorzen_core"
path = "src/lib.rs"
