[build]
target = "index.html"
dist = "dist"

[watch]
watch = ["src", "public"]
ignore = ["dist", "target"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

# Copy the entire public directory
[[copy]]
source = "public/"
dest = "./"

# Alternatively, if you want more control, copy specific files:
# [[copy]]
# source = "public/tailwind.css"
# dest = "tailwind.css"