[build]
target = "public/index.html"
dist = "dist"

[watch]
watch = ["src"]
ignore = ["dist", "target"]

[serve]
addresses = ["127.0.0.1"]
port = 8080
open = false

[[copy]]
source = "public/tailwind.css"
dest = "tailwind.css"
