[licenses]
allow = [
 "MIT",
 "Apache-2.0",
 "BSD-2-Clause",
 "BSD-3-Clause",
 "Unicode-3.0",
 "ISC"
]
[advisories]
ignore = []
[sources]
unknown-registry = "deny"
unknown-git = "warn"
# [licenses.exceptions]
# Example: allow a specific crate with a nonstandard license
# "crate-name@version" = { allow = ["Custom-License"] }
